services:
  - type: web
    name: raktasetu-backend
    runtime: python
    region: oregon
    rootDir: bloodwarriors-backend
    buildCommand: |
      pip install -r requirements.txt
      python seed_db.py --force
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: USE_MOCK_AI
        value: "True"
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
